### PR TITLE
Only consider license content until 'END OF TERMS AND CONDITIONS'

### PR DESCRIPTION
**Pull request by talisein**
The GPL licenses have 'How to apply to your program' instructions at the bottom of their file. This text is not the license itself, and some people remove the instructions when putting the LICENSE file in their repo.

### CODE REVIEW

**Comment by benbalter** [comment]
Thanks @talisein!

@mlinksva any strong feelings one way or the other?

**Comment by mlinksva** [comment]
Seems fine to me so long as it doesn't lead us to stop matching with instructions included. Are there tests for matching both normal and instructions-removed versions of the texts this truncates for matching purposes?

**Comment by mlinksva** [comment]
(Even if they match now, tests are important in case we separately decide to further tweak matching thresholds, etc.)

**Comment by talisein** [comment]
I added a test for matching when the repository under test is GPLv3 with no instructions. There are existing tests where the repository under test includes the instructions (e.g. fixtures/lgpl). If you would like me to create explicit tests for all the licenses this effects today (Apache, AGPL, LGPL, GPL) I don't mind, but it might clutter up the fixtures directory a little.

**Comment by benbalter** [comment]
The technical implementation is fine here (thanks @talisein). Between this and the [Apache boilerplate](https://github.com/benbalter/licensee/issues/103), I'm wondering if licenses (at least those two), should have an alternate form, which we could test. I'd prefer we test the versions that the vast majority use (which could result in an exact match, with 100% confidence) than a mangled version that's still above our 95% threshold (which we may one day want to raise or lower, which could result in false positive/negatives).

**Comment by benbalter** [comment]
>  I'd prefer we test the versions that the vast majority use (which could result in an exact match, with 100% confidence) than a mangled version that's still above our 95% threshold 

@talisein Looking at your implementation again, I changed my mind and like your approach. If a license says "END OF TERMS AND CONDITIONS", it should be safe to ignore anything after it from an enforceability perspective, and as long as we're doing it on both sides, as you are, the result should be the same.

I'm going to resolve the merge conflict and get this merged.

**Comment by benbalter** [comment]
@talisein Thanks for this. Resolved the merge conflict and merged via https://github.com/benbalter/licensee/pull/154.

**Pull request merged**
