### PR TITLE
Fixes to running licensee against a single file (on Windows)

### PR DESCRIPTION
**Pull request by sschuberth**
Please have a look at the individual commit messages for the details.

### CODE REVIEW

**Comment by benbalter** [comment]
Thanks @sschuberth!

**Comment by sschuberth** [comment]
Wow, you even merged it before the CI completed! 8-O

**Comment by sschuberth** [comment]
Hmm, looks like there were some failures on CI ...

**Comment by benbalter** [comment]
@sschuberth I was moving quickly and messed this one up good. Sorry about the hassle. Reverted via https://github.com/benbalter/licensee/pull/145. 

Are you able to open a new PR with the commits above?

**Pull request merged**
