### PR TITLE
Use Thor for the CLI

### PR DESCRIPTION
**Pull request by benbalter**
In https://github.com/benbalter/licensee/issues/267, @sschuberth made me realize that users were using the command line interface to use the license information in other languages. That makes total sense, and is something Licensee should support, but wasn't what the command was originally intended for (it was originally just a quick debug tool to use to diagnose undetected licenses). 

Technically, the old CLI output roughly parsed as YAML (an accident), and we didn't consider changes to the output breaking changes (even though it would have broken parsers).

This PR makes the command-line interface a first-class feature by moving it to Thor to make it more robust, add additional configuration flags, and ensure it's properly documented/tested.

Specifically:

### Command line help

```
➜  licensee git:(better-cli) ✗ licensee help
Licensee commands:
  licensee detect [PATH]        # Detect the license of the given project
  licensee diff [PATH]          # Compare the given license text to a known license
  licensee help [COMMAND]       # Describe available commands or one specific command
  licensee license-path [PATH]  # Returns the path to the given project's license file
  licensee version              # Return the Licensee version

Options:
  [--remote], [--no-remote]  # Assume PATH is a GitHub owner/repo path
```

### Command line flags

```
➜  licensee git:(better-cli) ✗ licensee help detect
Usage:
  licensee detect [PATH]

Options:
  [--json], [--no-json]          # Return output as JSON
  [--packages], [--no-packages]  # Detect licenses in package manager files
                                 # Default: true
  [--readme], [--no-readme]      # Detect licenses in README files
                                 # Default: true
  [--confidence=N]               # Confidence threshold
                                 # Default: 98
  [--license=LICENSE]            # The SPDX ID or key of the license to compare (implies --diff)
  [--diff], [--no-diff]          # Compare the license to the closest match
  [--remote], [--no-remote]      # Assume PATH is a GitHub owner/repo path

Detect the license of the given project
```
(and the flags are properly parsed in an order-agnostic way)

### Cleaner output

```
➜  licensee git:(better-cli) ✗ licensee detect
License:        MIT License
Matched files:  LICENSE.md, licensee.gemspec
LICENSE.md:
  Content hash:  46cdc03462b9af57968df67b450cc4372ac41f53
  Attribution:   Copyright (c) 2014-2017 Ben Balter
  Confidence:    100.00%
  Matcher:       Licensee::Matchers::Exact
  License:       MIT License
licensee.gemspec:
  Confidence:  90.00%
  Matcher:     Licensee::Matchers::Gemspec
  License:     MIT License
```

### JSON output

```
➜  licensee git:(better-cli) ✗ be licensee detect --json
{
   "licenses":[
      {
         "key":"mit",
         "spdx_id":"MIT",
         "meta":{
            "title":"MIT License",
            "source":"https://opensource.org/licenses/MIT",
            "description":"A short and simple permissive license with conditions only requiring preservation of copyright and license notices. Licensed works, modifications, and larger works may be distributed under different terms and without source code.",
            "how":"Create a text file (typically named LICENSE or LICENSE.txt) in the root of your source code and copy the text of the license into the file. Replace [year] with the current year and [fullname] with the name (or names) of the copyright holders.",
            "using":[
               {
                  "Babel":"https://github.com/babel/babel/blob/master/LICENSE"
               },
               {
                  ".NET Core":"https://github.com/dotnet/corefx/blob/master/LICENSE.TXT"
               },
               {
                  "Rails":"https://github.com/rails/rails/blob/master/MIT-LICENSE"
               }
            ],
            "featured":true,
            "hidden":false,
            "nickname":null,
            "note":null
         },
         "url":"http://choosealicense.com/licenses/mit/",
         "rules":{
            "permissions":[
               {
                  "tag":"commercial-use",
                  "label":"Commercial use",
                  "description":"This software and derivatives may be used for commercial purposes."
               },
               {
                  "tag":"modifications",
                  "label":"Modification",
                  "description":"This software may be modified."
               },
               {
                  "tag":"distribution",
                  "label":"Distribution",
                  "description":"This software may be distributed."
               },
               {
                  "tag":"private-use",
                  "label":"Private use",
                  "description":"This software may be used and modified in private."
               }
            ],
            "conditions":[
               {
                  "tag":"include-copyright",
                  "label":"License and copyright notice",
                  "description":"A copy of the license and copyright notice must be included with the software."
               }
            ],
            "limitations":[
               {
                  "tag":"liability",
                  "label":"Liability",
                  "description":"This license includes a limitation of liability."
               },
               {
                  "tag":"warranty",
                  "label":"Warranty",
                  "description":"The license explicitly states that it does NOT provide any warranty."
               }
            ]
         },
         "fields":[
            {
               "name":"year",
               "description":"The current year"
            },
            {
               "name":"fullname",
               "description":"The full name or username of the repository owner"
            }
         ],
         "other":false,
         "gpl":false,
         "lgpl":false,
         "cc":false
      }
   ],
   "matched_files":[
      {
         "filename":"LICENSE.md",
         "content":"MIT License\n\nCopyright (c) 2014-2017 Ben Balter\n\nPermission is hereby granted, free of charge, to any person obtaining a copy\nof this software and associated documentation files (the \"Software\"), to deal\nin the Software without restriction, including without limitation the rights\nto use, copy, modify, merge, publish, distribute, sublicense, and/or sell\ncopies of the Software, and to permit persons to whom the Software is\nfurnished to do so, subject to the following conditions:\n\nThe above copyright notice and this permission notice shall be included in all\ncopies or substantial portions of the Software.\n\nTHE SOFTWARE IS PROVIDED \"AS IS\", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR\nIMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,\nFITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE\nAUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER\nLIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,\nOUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE\nSOFTWARE.\n",
         "content_hash":"46cdc03462b9af57968df67b450cc4372ac41f53",
         "content_normalized":"permission is hereby granted, free of charge, to any person obtaining a copy of this software and associated documentation files the \"software\" , to deal in the software without restriction, including without limitation the rights to use, copy, modify, merge, publish, distribute, sublicense, and/or sell copies of the software, and to permit persons to whom the software is furnished to do so, subject to the following conditions: the above copyright notice and this permission notice shall be included in all copies or substantial portions of the software. the software is provided \"as is\", without warranty of any kind, express or implied, including but not limited to the warranties of merchantability, fitness for a particular purpose and noninfringement. in no event shall the authors or copyright holders be liable for any claim, damages or other liability, whether in an action of contract, tort or otherwise, arising from, out of or in connection with the software or the use or other dealings in the software.",
         "matcher":{
            "name":"Exact",
            "confidence":100
         },
         "matched_license":"mit"
      },
      {
         "filename":"licensee.gemspec",
         "content":"require File.expand_path('../lib/licensee/version', __FILE__)\n\nGem::Specification.new do |gem|\n  gem.name    = 'licensee'\n  gem.version = Licensee::VERSION\n\n  gem.summary = 'A Ruby Gem to detect open source project licenses'\n  gem.description = <<-DESC\n    Licensee automates the process of reading LICENSE files and\n    compares their contents to known licenses using a fancy maths.\n  DESC\n\n  gem.authors  = ['Ben Balter']\n  gem.email    = 'ben.balter@github.com'\n  gem.homepage = 'https://github.com/benbalter/licensee'\n  gem.license  = 'MIT'\n\n  gem.bindir = 'bin'\n  gem.executables << 'licensee'\n\n  gem.add_dependency('octokit', '~> 4.8.0')\n  gem.add_dependency('rugged', '~> 0.24')\n  gem.add_dependency('thor', '~> 0.19')\n  gem.add_dependency('dotenv', '~> 2.0')\n\n  gem.add_development_dependency('coveralls', '~> 0.8')\n  gem.add_development_dependency('mustache', '>= 0.9', '< 2.0')\n  gem.add_development_dependency('pry', '~> 0.9')\n  gem.add_development_dependency('rake', '~> 10.3')\n  gem.add_development_dependency('rspec', '~> 3.5')\n  gem.add_development_dependency('rubocop', '~> 0.49')\n  gem.add_development_dependency('webmock', '~> 3.1')\n\n  gem.required_ruby_version = '>= 2.1'\n\n  # ensure the gem is built out of versioned files\n  gem.files = Dir[\n    'Rakefile',\n    '{bin,lib,man,test,vendor,spec}/**/*',\n    'README*', 'LICENSE*'\n  ] & `git ls-files -z`.split(\"\\0\")\nend\n",
         "content_hash":null,
         "content_normalized":null,
         "matcher":{
            "name":"Gemspec",
            "confidence":90
         },
         "matched_license":"mit"
      }
   ]
}
```

...and tests (WIP).

To implement the JSON, each primary model now includes a shared `HashHelper` module, and exposes a `HASH_METHODS` constant. The `HashHelper` calls each hash method to recursively build a hash representing the model, which we can then call `.to_json` against. (I'm all ears if there's a better way).

Thoughts?

### TODO

- [ ] Tests
- [ ] Docs

### CODE REVIEW

**Comment by sschuberth** [comment]
I very much like that direction, thanks! Some random thoughts:

Does it really make sense to have all these `--no-*` flags for `detect`? Like, if I specified `--no-json`, in which format would be the output then? I'd rather make the default output valid YAML, very much like it coincidentally is now, and only have a `--json` flag to output JSON instead.

Similarly for `--(no-)packages` / `--(no-)readme`: If the default is `true` for each, why not only have the `--no-(packages|readme)` to disable looking at these, because I hardly can think of a case where I need to toggle these flags on and off within the same invocation of `detect`.

The `--(no-)diff` / `--(no-)remote` flags don't specify their default values.

Is the "Cleaner output" intended to lack the SPDX ID (again), and you're supported to use `--json` now if you want it?

Thanks for this again!

**Comment by benbalter** [comment]
> Does it really make sense to have all these --no-* flags for detect? Like, if I specified --no-json, in which format would be the output then? 

This is something that Thor (the CLI library) does, in case you'd like to explicitly set the boolean one way or the other (e.g., in case the default changes).

> Similarly for --(no-)packages / --(no-)readme: If the default is true for each, why not only have the --no-(packages|readme) to disable looking at these, because I hardly can think of a case where I need to toggle these flags on and off within the same invocation of detect.

Selfishly, I would use those two flags to debug GitHub.com detection, which does not take into account package managers or README files.

> I'd rather make the default output valid YAML, very much like it coincidentally is now, and only have a --json flag to output JSON instead.... Is the "Cleaner output" intended to lack the SPDX ID (again), and you're supported to use --json now if you want it?

The output was YAML-ish by accident. I had intended it to be human readable. I'm hesitant to make a commitment that the CLI output is going to be valid YAML as we may want to make changes to the human-readable output that would be considered breaking changes if parsed by a machine. Instead, I'd recommend pulling the JSON which we can control more strictly, type, etc. and can commit to SemVer for downstream consumers.

**Comment by sschuberth** [comment]
@benbalter, can we please get a new gem with Thor support?

**Comment by benbalter** [comment]
@sschuberth released https://github.com/benbalter/licensee/releases/tag/v9.9.0.beta.2. Would love some help testing the output in the wild before committing to non-breaking changes going forward.

**Comment by sschuberth** [comment]
@benbalter something seems to be wrong with the released 9.9.0.beta.2 package. If I do

    sudo gem install licensee -v 9.9.0.beta.2

then I get

    $ licensee help
    Licensee commands:
      licensee help [COMMAND]  # Describe available commands or one specific command

    Options:
      [--remote], [--no-remote]  # Assume PATH is a GitHub owner/repo path

whereas when running from source I get

    $ bundle exec bin/licensee help
    Licensee commands:
      licensee detect [PATH]        # Detect the license of the given project
      licensee diff [PATH]          # Compare the given license text to a known license
      licensee help [COMMAND]       # Describe available commands or one specific command
      licensee license-path [PATH]  # Returns the path to the given project's license file
      licensee version              # Return the Licensee version

    Options:
      [--remote], [--no-remote]  # Assume PATH is a GitHub owner/repo path

**Pull request merged**
