### PR TITLE
correct bad information about license notice in source files

### PR DESCRIPTION
**Pull request by ian-kelling**
https://www.gnu.org/licenses/identify-licenses-clearly.html:
"developers could release a program under GNU GPL
version 1 only, or release it under GPL version 1 or any later
version. The way developers state their choice is in the license notice
that goes at the start of each source file. That's where the GPL says
the decision is stated."

https://spdx.org/using-spdx#identifiers:
"The SPDX Work-group proposes to use SPDX license identifiers to
indicate the license at the file level."

### CODE REVIEW

**Comment by ale5000-git** [comment]
I think it is asking to detect whether it is "GNU General Public License v1.0 only" or "GNU General Public License v1.0 or later".

**Comment by mlinksva** [comment]
In c311866 I generalized @ian-kelling's edit, and also brought up to date: licensee for a long time has optionally looked at some of the things this file says it doesn't.

**Comment by ale5000-git** [comment]
This isn't true:
`It's a lot of work, as there's no standardized, cross-platform way to describe a _project's_ license within a source file comment`

There is a standard way to describe a project's license within a source file comment: https://spdx.org/using-spdx-license-identifier

**Comment by mlinksva** [comment]
Yes it is true. I emphasized project for exactly the reason you cite, @ale5000-git.

**Comment by benbalter** [comment]
@ale5000-git do you have an easy way to detect code comments across languages? If so, we could look into implementing this.

**Comment by ale5000-git** [comment]
@benbalter 
It could simply look for `SPDX-License-Identifier: ` text in source code comments.

Example for single license:
`SPDX-License-Identifier: GPL-2.0`
Example for multiple license:
`SPDX-License-Identifier: (LGPL-2.1 AND BSD-2-CLAUSE)`

The comment is usually in a separate line from other comments (but I'm not sure if it is the rule).
But it can be easily detected since the license identifier doesn't contain spaces so a space or newline end the identifier, if there are multiple licenses then there are also the brackets to help detecting the end.
You can find the exact specs in this pdf: https://spdx.org/sites/cpstandard/files/pages/files/using_spdx_license_list_short_identifiers.pdf

**Pull request merged**
